In [3]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output
import pygame

In [4]:
env = gym.make("FrozenLake-v1")

In [5]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [6]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [7]:
rewards_all_episodes = []

for episode in range(num_episodes):
    
    state = env.reset()[0]
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
        
        next_state, reward, terminated, truncated , info = env.step(action)
        
        done = truncated or terminated
        
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[next_state, :]))
        
        state = next_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    
    rewards_all_episodes.append(rewards_current_episode)

rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)

count = 1000

print('***Avg reward per 1000 episodes ***\n')
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

print(q_table)
    
        

C:\Users\Giorgos\anaconda3\envs\test_env1\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


***Avg reward per 1000 episodes ***

1000 :  0.05000000000000004
2000 :  0.23000000000000018
3000 :  0.4220000000000003
4000 :  0.5800000000000004
5000 :  0.6140000000000004
6000 :  0.6500000000000005
7000 :  0.6660000000000005
8000 :  0.7060000000000005
9000 :  0.6740000000000005
10000 :  0.6930000000000005
[[0.52402635 0.49241457 0.46888066 0.48779182]
 [0.42839483 0.2930975  0.2821123  0.4769314 ]
 [0.42345314 0.40850681 0.40933852 0.43543077]
 [0.2912091  0.34789586 0.34627473 0.42588447]
 [0.54557499 0.39087439 0.32278951 0.30289864]
 [0.         0.         0.         0.        ]
 [0.4148531  0.07807866 0.21469223 0.08309459]
 [0.         0.         0.         0.        ]
 [0.4398813  0.40551279 0.33403801 0.58409213]
 [0.37765516 0.62768228 0.35687525 0.33185862]
 [0.65867915 0.39394171 0.39517125 0.29191887]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.46206896 0.55291374 0.74114886 0.40105417]
 [0.71063884 0.85890508 0.731023

In [8]:
env = gym.make("FrozenLake-v1", render_mode="human")

for episode in range(3):
    state = env.reset()[0]
    done = False
    print("***Episode ", episode+1, "***\n\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])
        next_state, reward, terminated, truncated , info = env.step(action)
        done = terminated or truncated
        
        if done:
            clear_output(wait=True)
            env.render()
            
            if reward == 1 :
                print("Goal")
                time.sleep(0.3)
            else:
                print("Hole!")
                time.sleep(0.3)
            clear_output(wait=True)
            break
        
        state = next_state
        
env.close()
    

Goal
